import type { WizardAnswers, GeneratedFile, GeneratedFileKey } from '@/types'

// ===== CLAUDE.md テンプレート =====
function generateClaudeMd(answers: WizardAnswers): string {
  const { q1_projectType, q2_language, q3_teamSize, q4_reviewStyle, q5_tools, q6_instructionStyle } = answers

  const projectLabels: Record<string, string> = {
    web: 'Web アプリケーション',
    mobile: 'モバイルアプリ',
    cli: 'CLI / バックエンドサービス',
    data: 'データ / ML プロジェクト',
  }

  const langLabels: Record<string, string> = {
    typescript: 'TypeScript',
    javascript: 'JavaScript',
    python: 'Python',
    go: 'Go',
  }

  const teamLabels: Record<string, string> = {
    solo: '個人開発',
    small: '小規模チーム（2〜5人）',
    mid: '中規模チーム（6〜15人）',
    large: '大規模チーム（16人以上）',
  }

  const reviewLabels: Record<string, string> = {
    strict: '厳格（型安全・テスト・Lint 最優先）',
    standard: '標準（品質とスピードのバランス）',
    speed: 'スピード優先（プロトタイプ・迅速な反復）',
  }

  const isDetailed = q6_instructionStyle === 'detailed'
  const isCompact = q6_instructionStyle === 'compact'

  let content = `# CLAUDE.md
<!-- Generated by WeMAI — Powered by Claude (Anthropic) -->

## Project Overview

This is a **${projectLabels[q1_projectType] || q1_projectType}** project using **${langLabels[q2_language] || q2_language}**.

- Team: ${teamLabels[q3_teamSize] || q3_teamSize}
- Code review style: ${reviewLabels[q4_reviewStyle] || q4_reviewStyle}
`

  if (q5_tools.length > 0) {
    content += `\n## Integrated Tools\n\n`
    q5_tools.forEach((tool) => {
      content += `- ${tool.charAt(0).toUpperCase() + tool.slice(1)}\n`
    })
  }

  content += `\n## Development Guidelines\n\n`

  if (q4_reviewStyle === 'strict' || isDetailed) {
    content += `### Code Quality
- Enforce strict TypeScript / type checking
- Maintain test coverage above 80%
- All code must pass Lint before committing
- Follow SOLID principles and clean architecture

### Commit Rules
- Use Conventional Commits format (feat:, fix:, docs:, etc.)
- Keep commits atomic and focused
- Write clear, descriptive commit messages in Japanese or English

`
  } else if (q4_reviewStyle === 'standard') {
    content += `### Code Quality
- Use TypeScript where possible
- Write tests for critical paths
- Follow project Lint rules
- Keep functions small and focused

`
  } else {
    content += `### Code Quality
- Move fast and iterate
- Write tests when time permits
- Prefer readable code over premature optimization

`
  }

  if (!isCompact) {
    content += `## Communication Style

- Respond in **Japanese** unless the code context requires English
- Explain reasoning before making significant changes
- Suggest alternatives when multiple approaches exist
- Flag potential issues proactively

`
  }

  content += `## Notes

- This file was generated by WeMAI (Welcome My AI)
- Powered by Claude (Anthropic) — https://claude.ai
- Generated: ${new Date().toISOString().split('T')[0]}
`

  return content
}

// ===== settings.json テンプレート =====
function generateSettings(answers: WizardAnswers): string {
  const { q4_reviewStyle, q3_teamSize } = answers

  const isStrict = q4_reviewStyle === 'strict'
  const isLargeTeam = ['mid', 'large'].includes(q3_teamSize)

  const settings = {
    permissions: {
      allow: ['read', 'write', ...(isStrict ? [] : ['execute'])],
      deny: ['network', ...(isLargeTeam ? ['delete'] : [])],
    },
    model: 'claude-sonnet-4-5',
    maxTokens: isStrict ? 4096 : 8192,
    language: 'ja',
    autoApprove: q4_reviewStyle === 'speed',
    ...(isStrict && {
      hooks: {
        preCommit: 'npm run lint && npm run test',
      },
    }),
  }

  return JSON.stringify(settings, null, 2)
}

// ===== mcp_config.json テンプレート =====
function generateMcpConfig(answers: WizardAnswers): string {
  const { q5_tools } = answers
  const mcpServers: Record<string, unknown> = {}

  if (q5_tools.includes('github')) {
    mcpServers.github = {
      command: 'npx',
      args: ['-y', '@modelcontextprotocol/server-github'],
      env: { GITHUB_TOKEN: 'YOUR_GITHUB_TOKEN' },
    }
  }

  if (q5_tools.includes('slack')) {
    mcpServers.slack = {
      command: 'npx',
      args: ['-y', '@modelcontextprotocol/server-slack'],
      env: {
        SLACK_BOT_TOKEN: 'YOUR_SLACK_BOT_TOKEN',
        SLACK_TEAM_ID: 'YOUR_TEAM_ID',
      },
    }
  }

  if (q5_tools.includes('notion')) {
    mcpServers.notion = {
      command: 'npx',
      args: ['-y', '@modelcontextprotocol/server-notion'],
      env: { NOTION_API_KEY: 'YOUR_NOTION_API_KEY' },
    }
  }

  if (q5_tools.includes('figma')) {
    mcpServers.figma = {
      command: 'npx',
      args: ['-y', '@modelcontextprotocol/server-figma'],
      env: { FIGMA_ACCESS_TOKEN: 'YOUR_FIGMA_TOKEN' },
    }
  }

  const config = {
    mcpServers:
      Object.keys(mcpServers).length > 0
        ? mcpServers
        : { _note: 'No tools selected. Add MCP servers here.' },
  }

  return JSON.stringify(config, null, 2)
}

// ===== slash_commands.md テンプレート =====
function generateSlashCommands(answers: WizardAnswers): string {
  const { q1_projectType, q2_language, q4_reviewStyle } = answers

  const isWeb = q1_projectType === 'web'
  const isData = q1_projectType === 'data'
  const isStrict = q4_reviewStyle === 'strict'

  let content = `# Slash Commands
<!-- Generated by WeMAI — Powered by Claude (Anthropic) -->

## 利用可能なカスタムコマンド

`

  content += `/review
コードレビューを実行します。${isStrict ? '型安全性・テストカバレッジ・Lint を含む包括的なレビュー。' : '主要なコード品質の問題を確認。'}

/test
${q2_language === 'python' ? 'pytest を使用して' : 'Jest/Vitest で'}ユニットテストを生成します。エッジケースを含む。

/doc
${q2_language === 'typescript' || q2_language === 'javascript' ? 'JSDoc' : 'Docstring'} ドキュメントを現在のファイルに生成します。

/refactor
コードのリファクタリング提案を行います。可読性・パフォーマンス・保守性を改善。

`

  if (isWeb) {
    content += `/component
新しい React コンポーネントを生成します。Props 型定義・スタイル・テストを含む。

/api
Next.js API ルートのスキャフォールドを生成します。バリデーション・エラーハンドリングを含む。

`
  }

  if (isData) {
    content += `/eda
データセットの探索的分析（EDA）を実行します。統計サマリー・可視化提案を含む。

/pipeline
データパイプラインのスキャフォールドを生成します。

`
  }

  content += `## 使い方

Claude Code のチャットで \`/\` + コマンド名を入力してください。

---
*Generated: ${new Date().toISOString().split('T')[0]} | WeMAI v1.0*
`

  return content
}

// ===== メイン生成関数 =====
export function generateFiles(
  answers: WizardAnswers,
  requestedFiles: GeneratedFileKey[],
): GeneratedFile[] {
  const generators: Record<GeneratedFileKey, () => string> = {
    'CLAUDE.md': () => generateClaudeMd(answers),
    'settings.json': () => generateSettings(answers),
    'mcp_config.json': () => generateMcpConfig(answers),
    'slash_commands.md': () => generateSlashCommands(answers),
  }

  const proFiles: GeneratedFileKey[] = ['mcp_config.json', 'slash_commands.md']

  return requestedFiles.map((key) => ({
    key,
    filename: key,
    content: generators[key](),
    isPro: proFiles.includes(key),
  }))
}
